/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpages;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ellan
 */
public class acchistory extends javax.swing.JInternalFrame {

    /**
     * Creates new form acchistory
     */
    public acchistory() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI)this.getUI();
        bif.setNorthPane(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prankd = new javax.swing.JLabel();
        prankd2 = new javax.swing.JLabel();
        prankd3 = new javax.swing.JLabel();
        plat1 = new javax.swing.JLabel();
        laf = new javax.swing.JLabel();
        cocogigil = new javax.swing.JLabel();
        kapematapang = new javax.swing.JLabel();
        cocodila = new javax.swing.JLabel();
        motiv = new javax.swing.JLabel();
        laf1 = new javax.swing.JLabel();
        cocokili = new javax.swing.JLabel();
        valak = new javax.swing.JLabel();
        negshak2 = new javax.swing.JLabel();
        negshak = new javax.swing.JLabel();
        uwukid = new javax.swing.JLabel();
        wallysad = new javax.swing.JLabel();
        charizard = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(128, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(128, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prankd.setText("prank'd");
        jPanel1.add(prankd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        prankd2.setText("prank'd");
        jPanel1.add(prankd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));

        prankd3.setText("prank'd");
        jPanel1.add(prankd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, -1, -1));

        plat1.setText("plat 1 automatic");
        jPanel1.add(plat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, 20));

        laf.setText("tumawa ka!");
        jPanel1.add(laf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, 20));

        cocogigil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/images-removebg-preview (5).png"))); // NOI18N
        jPanel1.add(cocogigil, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        kapematapang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/download-removebg-preview (5).png"))); // NOI18N
        jPanel1.add(kapematapang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, 220));

        cocodila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/images-removebg-preview (4).png"))); // NOI18N
        jPanel1.add(cocodila, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 320, -1, -1));

        motiv.setText("may plus points ka dahil nakita mo to!");
        jPanel1.add(motiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, 20));

        laf1.setText("deserv moto");
        jPanel1.add(laf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, 20));

        cocokili.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/52f0aea60368c528d83a66ded066e2cb_c5_720x720-removebg-preview.png"))); // NOI18N
        jPanel1.add(cocokili, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -70, 490, 640));

        valak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/Valak-removebg-preview.png"))); // NOI18N
        jPanel1.add(valak, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 90, 510, 290));

        negshak2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/download-removebg-preview (3).png"))); // NOI18N
        jPanel1.add(negshak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, -60, 230, -1));

        negshak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/download-removebg-preview (2).png"))); // NOI18N
        jPanel1.add(negshak, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, -10, 150, -1));

        uwukid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/download-removebg-preview (4).png"))); // NOI18N
        jPanel1.add(uwukid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, -10, 180, 200));

        wallysad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/download-removebg-preview (6).png"))); // NOI18N
        jPanel1.add(wallysad, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 260, -1));

        charizard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/download-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(charizard, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 180, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/images-removebg-preview (9).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, -70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel charizard;
    private javax.swing.JLabel cocodila;
    private javax.swing.JLabel cocogigil;
    private javax.swing.JLabel cocokili;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kapematapang;
    private javax.swing.JLabel laf;
    private javax.swing.JLabel laf1;
    private javax.swing.JLabel motiv;
    private javax.swing.JLabel negshak;
    private javax.swing.JLabel negshak2;
    private javax.swing.JLabel plat1;
    private javax.swing.JLabel prankd;
    private javax.swing.JLabel prankd2;
    private javax.swing.JLabel prankd3;
    private javax.swing.JLabel uwukid;
    private javax.swing.JLabel valak;
    private javax.swing.JLabel wallysad;
    // End of variables declaration//GEN-END:variables
}
