/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalpages;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author ellan
 */
public class dashboard extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bif = (BasicInternalFrameUI)this.getUI();
        bif.setNorthPane(null);
    }
    
        Color navcol = new Color(128,0,0);
        Color headercol = new Color(255,0,0);
        Color mainbodcol = new Color(102,0,0);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dashboardpane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        tableres = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        calendar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        time = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardpane.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout dashboardpaneLayout = new javax.swing.GroupLayout(dashboardpane);
        dashboardpane.setLayout(dashboardpaneLayout);
        dashboardpaneLayout.setHorizontalGroup(
            dashboardpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        dashboardpaneLayout.setVerticalGroup(
            dashboardpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        jPanel1.add(dashboardpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 720, 410));

        jPanel2.setBackground(new java.awt.Color(128, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableres.setBackground(new java.awt.Color(102, 0, 0));
        tableres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableresMouseExited(evt);
            }
        });
        tableres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Table Reservation");
        tableres.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/icons8-reservation-65.png"))); // NOI18N
        tableres.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 40));

        jPanel2.add(tableres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 80));

        calendar.setBackground(new java.awt.Color(102, 0, 0));
        calendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calendarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calendarMouseExited(evt);
            }
        });
        calendar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Open Calendar");
        calendar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/icons8-tear-off-calendar-60.png"))); // NOI18N
        calendar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 50));

        jPanel2.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 240, 80));

        time.setBackground(new java.awt.Color(102, 0, 0));
        time.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timeMouseExited(evt);
            }
        });
        time.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pick Time");
        time.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgnicons/icons8-clock-55.png"))); // NOI18N
        time.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 40));

        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 240, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseEntered
        time.setBackground(navcol);
    }//GEN-LAST:event_timeMouseEntered

    private void timeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseExited
        time.setBackground(mainbodcol);
    }//GEN-LAST:event_timeMouseExited

    private void tableresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresMouseEntered
       tableres.setBackground(navcol);
    }//GEN-LAST:event_tableresMouseEntered

    private void tableresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresMouseExited
        tableres.setBackground(mainbodcol);
    }//GEN-LAST:event_tableresMouseExited

    private void calendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMouseEntered
       calendar.setBackground(navcol);
    }//GEN-LAST:event_calendarMouseEntered

    private void calendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMouseExited
       calendar.setBackground(mainbodcol);
    }//GEN-LAST:event_calendarMouseExited

    private void tableresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableresMouseClicked
        dashboardtr dbtr = new dashboardtr();
        dashboardpane.add(dbtr).setVisible(true);
    }//GEN-LAST:event_tableresMouseClicked

    private void calendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarMouseClicked
       opencalendar opcal = new opencalendar();
        dashboardpane.add(opcal).setVisible(true);
    }//GEN-LAST:event_calendarMouseClicked

    private void timeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeMouseClicked
        timepage timep = new timepage();
        dashboardpane.add(timep).setVisible(true);
    }//GEN-LAST:event_timeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calendar;
    private javax.swing.JDesktopPane dashboardpane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel tableres;
    private javax.swing.JPanel time;
    // End of variables declaration//GEN-END:variables
}
